/* eslint-disable no-undef */
describe("Login", function() {
  it("Sign up", function() {
    cy.visit("http://localhost/")
    cy.get("[data-cy=signup]").click()
    cy.url().should("include", "/accounts/signup")
    cy.get("input[name$='username']")
      .type("user1")
      .should("have.value", "user1")
    cy.get("input[name$='email']")
      .type("user1@gmail.com")
      .should("have.value", "user1@gmail.com")
    cy.get("input[name$='password1']")
      .type("Ahmed.va.2000")
      .should("have.value", "Ahmed.va.2000")
    cy.get("input[name$='password2']")
      .type("Ahmed.va.2000")
      .should("have.value", "Ahmed.va.2000")
    cy.get("button[type$='submit']").click()
    cy.url().should("include", "/projects/")
    cy.contains("user1").click()
    cy.get("a[href*='/accounts/logout']").click()
    cy.url().should("include", "/accounts/login")
  })
  it("Login", function() {
    cy.visit("http://localhost/")
    cy.get("[data-cy=login]").click()
    cy.url().should("include", "/accounts/login")
    cy.get("input[name$='username']")
      .type("user1")
      .should("have.value", "user1")
    cy.get("input[name$='password']")
      .type("Ahmed.va.2000")
      .should("have.value", "Ahmed.va.2000")
    cy.get("button[type$='submit']").click()
    cy.url().should("include", "/projects/")
    cy.get("[data-cy=newItem]").click()
    cy.get("[data-cy=name]")
      .type("project 1")
      .should("have.value", "project 1")
    cy.get("[data-cy=save]").click()
    cy.request("/api/users/delt/").then(response => {
      expect(response.status).to.eq(204)
    })
  })
})
